import { Config } from "effect"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

function falsy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "false" || value === "0"
}

function number(key: string) {
  const value = process.env[key]
  if (!value) return undefined
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

const PREMISE_EXPERIMENTAL = truthy("PREMISE_EXPERIMENTAL")
const PREMISE_DISABLE_CLAUDE_CODE = truthy("PREMISE_DISABLE_CLAUDE_CODE")
const PREMISE_DISABLE_CLAUDE_CODE_SKILLS =
  PREMISE_DISABLE_CLAUDE_CODE || truthy("PREMISE_DISABLE_CLAUDE_CODE_SKILLS")
const copy = process.env["PREMISE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  PREMISE_AUTO_SHARE: truthy("PREMISE_AUTO_SHARE"),
  PREMISE_AUTO_HEAP_SNAPSHOT: truthy("PREMISE_AUTO_HEAP_SNAPSHOT"),
  PREMISE_GIT_BASH_PATH: process.env["PREMISE_GIT_BASH_PATH"],
  PREMISE_CONFIG: process.env["PREMISE_CONFIG"],
  PREMISE_CONFIG_CONTENT: process.env["PREMISE_CONFIG_CONTENT"],
  PREMISE_DISABLE_AUTOUPDATE: truthy("PREMISE_DISABLE_AUTOUPDATE"),
  PREMISE_ALWAYS_NOTIFY_UPDATE: truthy("PREMISE_ALWAYS_NOTIFY_UPDATE"),
  PREMISE_DISABLE_PRUNE: truthy("PREMISE_DISABLE_PRUNE"),
  PREMISE_DISABLE_TERMINAL_TITLE: truthy("PREMISE_DISABLE_TERMINAL_TITLE"),
  PREMISE_SHOW_TTFD: truthy("PREMISE_SHOW_TTFD"),
  PREMISE_PERMISSION: process.env["PREMISE_PERMISSION"],
  PREMISE_DISABLE_DEFAULT_PLUGINS: truthy("PREMISE_DISABLE_DEFAULT_PLUGINS"),
  PREMISE_DISABLE_LSP_DOWNLOAD: truthy("PREMISE_DISABLE_LSP_DOWNLOAD"),
  PREMISE_ENABLE_EXPERIMENTAL_MODELS: truthy("PREMISE_ENABLE_EXPERIMENTAL_MODELS"),
  PREMISE_DISABLE_AUTOCOMPACT: truthy("PREMISE_DISABLE_AUTOCOMPACT"),
  PREMISE_DISABLE_MODELS_FETCH: truthy("PREMISE_DISABLE_MODELS_FETCH"),
  PREMISE_DISABLE_MOUSE: truthy("PREMISE_DISABLE_MOUSE"),
  PREMISE_DISABLE_CLAUDE_CODE,
  PREMISE_DISABLE_CLAUDE_CODE_PROMPT: PREMISE_DISABLE_CLAUDE_CODE || truthy("PREMISE_DISABLE_CLAUDE_CODE_PROMPT"),
  PREMISE_DISABLE_CLAUDE_CODE_SKILLS,
  PREMISE_DISABLE_EXTERNAL_SKILLS: truthy("PREMISE_DISABLE_EXTERNAL_SKILLS"),
  PREMISE_FAKE_VCS: process.env["PREMISE_FAKE_VCS"],
  PREMISE_SERVER_PASSWORD: process.env["PREMISE_SERVER_PASSWORD"],
  PREMISE_SERVER_USERNAME: process.env["PREMISE_SERVER_USERNAME"],
  PREMISE_ENABLE_QUESTION_TOOL: truthy("PREMISE_ENABLE_QUESTION_TOOL"),

  // Experimental
  PREMISE_EXPERIMENTAL,
  PREMISE_EXPERIMENTAL_FILEWATCHER: Config.boolean("PREMISE_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  PREMISE_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("PREMISE_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  PREMISE_EXPERIMENTAL_ICON_DISCOVERY: PREMISE_EXPERIMENTAL || truthy("PREMISE_EXPERIMENTAL_ICON_DISCOVERY"),
  PREMISE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("PREMISE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  PREMISE_ENABLE_EXA: truthy("PREMISE_ENABLE_EXA") || PREMISE_EXPERIMENTAL || truthy("PREMISE_EXPERIMENTAL_EXA"),
  PREMISE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: number("PREMISE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"),
  PREMISE_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number("PREMISE_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),
  PREMISE_EXPERIMENTAL_OXFMT: PREMISE_EXPERIMENTAL || truthy("PREMISE_EXPERIMENTAL_OXFMT"),
  PREMISE_EXPERIMENTAL_LSP_TY: truthy("PREMISE_EXPERIMENTAL_LSP_TY"),
  PREMISE_EXPERIMENTAL_LSP_TOOL: PREMISE_EXPERIMENTAL || truthy("PREMISE_EXPERIMENTAL_LSP_TOOL"),
  PREMISE_EXPERIMENTAL_PLAN_MODE: PREMISE_EXPERIMENTAL || truthy("PREMISE_EXPERIMENTAL_PLAN_MODE"),
  PREMISE_EXPERIMENTAL_MARKDOWN: !falsy("PREMISE_EXPERIMENTAL_MARKDOWN"),
  PREMISE_MODELS_URL: process.env["PREMISE_MODELS_URL"],
  PREMISE_MODELS_PATH: process.env["PREMISE_MODELS_PATH"],
  PREMISE_DISABLE_EMBEDDED_WEB_UI: truthy("PREMISE_DISABLE_EMBEDDED_WEB_UI"),
  PREMISE_DB: process.env["PREMISE_DB"],
  PREMISE_DISABLE_CHANNEL_DB: truthy("PREMISE_DISABLE_CHANNEL_DB"),
  PREMISE_SKIP_MIGRATIONS: truthy("PREMISE_SKIP_MIGRATIONS"),
  PREMISE_STRICT_CONFIG_DEPS: truthy("PREMISE_STRICT_CONFIG_DEPS"),

  PREMISE_WORKSPACE_ID: process.env["PREMISE_WORKSPACE_ID"],
  PREMISE_EXPERIMENTAL_HTTPAPI: truthy("PREMISE_EXPERIMENTAL_HTTPAPI"),
  PREMISE_EXPERIMENTAL_WORKSPACES: PREMISE_EXPERIMENTAL || truthy("PREMISE_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get PREMISE_DISABLE_PROJECT_CONFIG() {
    return truthy("PREMISE_DISABLE_PROJECT_CONFIG")
  },
  get PREMISE_TUI_CONFIG() {
    return process.env["PREMISE_TUI_CONFIG"]
  },
  get PREMISE_CONFIG_DIR() {
    return process.env["PREMISE_CONFIG_DIR"]
  },
  get PREMISE_PURE() {
    return truthy("PREMISE_PURE")
  },
  get PREMISE_PLUGIN_META_FILE() {
    return process.env["PREMISE_PLUGIN_META_FILE"]
  },
  get PREMISE_CLIENT() {
    return process.env["PREMISE_CLIENT"] ?? "cli"
  },
}
